# Generated by Django 4.1.7 on 2023-03-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productbrand_productcolor_producttags_producttype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttags",
            name="tagged_products",
            field=models.ManyToManyField(
                blank=True, related_name="product_tags", to="store.product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.producttags"
            ),
        ),
    ]
