# Generated by Django 4.1.7 on 2023-03-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_producttags_tagged_products_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsize",
            name="sized_products",
            field=models.ManyToManyField(
                blank=True, related_name="product_sizes", to="store.product"
            ),
        ),
        migrations.RemoveField(model_name="product", name="size",),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.productsize"
            ),
        ),
    ]
