# Generated by Django 4.1.7 on 2023-03-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_color_product_color"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="color",),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.productcolor",
            ),
        ),
    ]
