# Generated by Django 4.1.7 on 2023-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_product_color_product_color"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="color",),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.productcolor"
            ),
        ),
    ]
