# Generated by Django 4.1.7 on 2023-03-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_product_color_product_color"),
    ]

    operations = [
        migrations.RemoveField(model_name="productsize", name="sized_products",),
        migrations.RemoveField(model_name="producttags", name="tagged_products",),
    ]
