# Generated by Django 4.1.7 on 2023-03-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_productsize_sized_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolor",
            name="colored_products",
            field=models.ManyToManyField(
                blank=True, related_name="product_colors", to="store.product"
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="sized_products",
            field=models.ManyToManyField(
                blank=True, related_name="product_sizes", to="store.product"
            ),
        ),
        migrations.AddField(
            model_name="producttags",
            name="tagged_products",
            field=models.ManyToManyField(
                blank=True, related_name="product_tags", to="store.product"
            ),
        ),
    ]
