# Generated by Django 4.1.7 on 2023-03-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_productcolor_colored_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="productcolor", name="colored_products",),
        migrations.RemoveField(model_name="productsize", name="sized_products",),
        migrations.RemoveField(model_name="producttags", name="tagged_products",),
    ]
