# Generated by Django 4.1.7 on 2023-03-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_productcolor_colored_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True, unique=True
            ),
        ),
    ]
