# Generated by Django 4.1.7 on 2023-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbrand",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="producttags",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
