# Generated by Django 4.1.7 on 2023-03-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_productbrand_name_alter_producttags_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="color",),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.productcolor",
            ),
        ),
    ]
