# Generated by Django 4.1.7 on 2023-03-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_remove_product_color_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
