# Generated by Django 4.1.7 on 2023-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_product_discount_product_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.IntegerField(),
        ),
    ]
