# Generated by Django 4.1.7 on 2023-03-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_product_discount"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="size",),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.productsize",
            ),
        ),
    ]
