# Generated by Django 4.1.7 on 2023-03-29 10:00

from django.db import migrations, models
import django.db.models.deletion
import model_clone.mixin


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_alter_product_sku"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="color",),
        migrations.RemoveField(model_name="product", name="description",),
        migrations.RemoveField(model_name="product", name="discount",),
        migrations.RemoveField(model_name="product", name="discount_price",),
        migrations.RemoveField(model_name="product", name="is_active",),
        migrations.RemoveField(model_name="product", name="price",),
        migrations.RemoveField(model_name="product", name="product_type",),
        migrations.RemoveField(model_name="product", name="size",),
        migrations.RemoveField(model_name="product", name="sku",),
        migrations.RemoveField(model_name="product", name="stock",),
        migrations.RemoveField(model_name="product", name="variation_category",),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200, unique=True)),
                (
                    "images",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/products/variations"
                    ),
                ),
                ("stock", models.IntegerField()),
                ("price", models.IntegerField()),
                ("discount", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "discount_price",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productcolor",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productsize",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variation",
                "verbose_name_plural": "Product Variations",
                "ordering": ["-product", "-product_name", "-size", "-color"],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
