# Generated by Django 4.1.7 on 2023-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="variation_name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="variation",
            name="product_name",
            field=models.CharField(max_length=200),
        ),
    ]
