# Generated by Django 4.1.7 on 2023-03-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem", old_name="active", new_name="is_active",
        ),
    ]
