# Generated by Django 4.1.7 on 2023-03-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_rename_active_cartitem_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["date_added"],
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "CartItem", "verbose_name_plural": "CartItems"},
        ),
        migrations.AlterModelTable(name="cart", table="Cart",),
        migrations.AlterModelTable(name="cartitem", table="CartItem",),
    ]
