# Generated by Django 4.1.7 on 2023-03-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Cart Item", "verbose_name_plural": "Cart Items"},
        ),
    ]
