# Generated by Django 4.1.7 on 2023-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_alter_cartitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
