# Generated by Django 4.1.7 on 2023-03-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_product_product_type"),
        ("carts", "0006_alter_cartitem_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.variation"
            ),
        ),
    ]
