# Generated by Django 4.1.7 on 2023-03-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_variation_variation_name_and_more"),
        ("carts", "0008_cartitem_variation_alter_cartitem_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartitem", name="variation",),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.variation"
            ),
        ),
    ]
