# Generated by Django 4.1.7 on 2023-03-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_variation_variation_name_and_more"),
        ("wishlists", "0003_alter_wishlistitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.variation"
            ),
        ),
    ]
